import { useEffect, useRef, useState } from 'react';
import { Check, ChevronDown, Eye, Search, SlidersHorizontal } from 'lucide-react';
import type { Model } from '../types';
export default function ModelPicker({ models, value, onChange, disabled, isAdmin, onSettings }: { models: Model[]; value: string; onChange: (id: string) => void; disabled: boolean; isAdmin: boolean; onSettings: () => void }) {
  const [open, setOpen] = useState(false); const [query, setQuery] = useState(''); const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { const close = (e: MouseEvent) => { if (!ref.current?.contains(e.target as Node)) setOpen(false); }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close); }, []);
  useEffect(() => { const escape = (event: KeyboardEvent) => { if (event.key === 'Escape' && open) { setOpen(false); ref.current?.querySelector<HTMLButtonElement>('.model-trigger')?.focus(); } }; document.addEventListener('keydown',escape); return () => document.removeEventListener('keydown',escape); }, [open]);
  const selected = models.find(m => m.id === value);
  return <div className="model-picker" ref={ref}><button className="model-trigger" onClick={() => setOpen(!open)} disabled={disabled} aria-label="选择模型" aria-haspopup="dialog" aria-expanded={open}>{selected?.name || 'APIRouter'}<ChevronDown size={16} className={open ? 'rotated' : ''}/></button>{open && <div className="model-menu popover" role="dialog" aria-label="选择模型"><div className="menu-heading">可用模型 <span>{models.length}</span></div>{models.length > 4 && <div className="search-input"><Search size={16}/><input autoFocus placeholder="搜索模型" value={query} onChange={e => setQuery(e.target.value)}/></div>}<div className="model-options">{models.filter(m => `${m.name} ${m.modelId}`.toLowerCase().includes(query.toLowerCase())).map(model => <button className={`model-option ${value === model.id ? 'chosen' : ''}`} key={model.id} onClick={() => { onChange(model.id); setOpen(false); }}><div><strong>{model.name}</strong><span>{model.vision ? <><Eye size={12}/> 支持图片</> : '文字与文档'}</span></div>{value === model.id && <Check size={17}/>}</button>)}{models.length === 0 && <p className="menu-empty">暂时没有启用的模型。{isAdmin ? '请先连接 API。' : '请联系管理员配置。'}</p>}</div>{isAdmin && <button className="menu-footer" onClick={() => { setOpen(false); onSettings(); }}><SlidersHorizontal size={15}/> 管理模型</button>}</div>}</div>;
}
